name: ddd_feed
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  bloc: ^8.1.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_hooks: ^0.18.6
  flutter_launcher_icons: ^0.13.0
  flutter_native_splash: ^2.2.19
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  google_fonts: ^4.0.3
  heroicons: ^0.8.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^0.8.7+3
  injectable: ^2.1.1
  timeago: ^3.4.0

dev_dependencies:
  analyzer: ^5.10.0
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  hive_generator: ^2.0.0
  injectable_generator: ^2.1.5

flutter_icons:
  android: true
  ios: true
  remPove_alpha_ios: true
  image_path: "assets/logos/circle_logo.png"

flutter_native_splash:
  image: "assets/logos/circle_logo.png"
  color: "#FFFFFF"
  fullscreen: true

flutter:
  uses-material-design: true
